const sampleFoodData = [
    {
        id: 1,
        name: "Margherita Pizza",
        description: "Classic delight with mozzarella cheese",
        price: 299,
        category: "Pizza",
        isVeg: true,
        image: "https://imgs.search.brave.com/ZxbYvptKsdMMRLwvljfwgFFicaLPUb3r_4TPncAyH0w/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90YW1t/eWNpcmNlby5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMjIv/MDgvSU1HXzc4MDQt/Vy03MzF4MTAyNC5q/cGc",
        rating: 4.5,
    },
    {
        id: 2,
        name: "Chicken Biryani",
        description: "Aromatic basmati rice with tender chicken",
        price: 349,
        category: "Rice",
        isVeg: false,
        image: "https://imgs.search.brave.com/_uRSkW0RB8qguVDZWpyrP5OIw-jQ6J1oEcxqNY9Eek0/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTA1/ODAyOTA5Ni9waG90/by9jaGlja2VuLWJp/cnlhbmkuanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPXlWVjFS/QXJrWXoxZlhmMEJs/cGV1d3h0MHlUSEhE/bmxPVVJWTUptWWdB/ZUk9",
        rating: 4.7,
    },
    {
        id: 3,
        name: "Veg Burger",
        description: "Loaded with fresh veggies and cheese",
        price: 149,
        category: "Burger",
        isVeg: true,
        image: "https://imgs.search.brave.com/HYyXnN9JMi_UvDwHJgJjpEizzQG-N2iR8iD-o-C-7SE/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvNTEx/OTIzMzcyL3Bob3Rv/L3ZlZ2dpZS1idXJn/ZXIuanBnP3M9NjEy/eDYxMiZ3PTAmaz0y/MCZjPTRwa1JUSXlx/ejY4YmZIOE0zWDBW/Z0dIMlNpcVllbG1L/SWY3WS01OGhLU0U9",
        rating: 4.2,
    },
    {
        id: 4,
        name: "Pasta Alfredo",
        description: "Creamy white sauce pasta with mushrooms",
        price: 259,
        category: "Pasta",
        isVeg: true,
        image: "https://imgs.search.brave.com/XOyavx4s9A9sCoKgxBqbFmJpNEv_XmOQeuobMbG9g8w/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuaW1tZWRpYXRl/LmNvLnVrL3Byb2R1/Y3Rpb24vdm9sYXRp/bGUvc2l0ZXMvMzAv/MjAyMi8wOC9BbGZy/ZWRvLWRjNjYyZTMu/anBnP3F1YWxpdHk9/OTAmcmVzaXplPTU1/Niw1MDU",
        rating: 4.3,
    },
    {
        id: 7,
        name: 'Paneer Tikka',
        description: 'Grilled cottage cheese with a tangy marinade.',
        price: '200',
        isVeg: true,
        image: 'https://imgs.search.brave.com/5txkvAu_7j-EzL1Jiuh3Lyo4AYO7kvLlELCqA6U3j-A/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzA5Lzc1LzYzLzk1/LzM2MF9GXzk3NTYz/OTU3M196cDFJVWN1/Y2pOZ081djJZa2d6/UU43cU5QcjI5aHY4/dS5qcGc',
        rating: 4.3,
    },
    {
        id: 7,
        name: 'Momos',
        description: 'Grilled cottage cheese with a tangy marinade.',
        price: '200',
        isVeg: true,
        image: 'https://imgs.search.brave.com/WeZxsKfA-FDPmSQBym4gohpYVTwWemnGZd2xE-DhLc4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzA3Lzk0LzMzLzUx/LzM2MF9GXzc5NDMz/NTEzOV9jQlJUdXJ3/TXQ5M0pmQVBTQkhm/aWxGaU92N2t3WGFo/NC5qcGc',
        rating: 4.3,
    },
    {
        id: 7,
        name: 'Mushroom Fried Rice',
        description: 'Grilled cottage cheese with a tangy marinade.',
        price: '200',
        isVeg: true,
        image: 'https://imgs.search.brave.com/5PisoGXslRf_PHPgBv_m46GeU2rL1ZS3XNohORWiLy0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/aW5kaWFuaGVhbHRo/eXJlY2lwZXMuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDIx/LzExL211c2hyb29t/LWZyaWVkLXJpY2Uu/d2VicA',
        rating: 4.3,
    },
    {
        id: 7,
        name: 'Momos',
        description: 'Grilled cottage cheese with a tangy marinade.',
        price: '200',
        isVeg: true,
        image: 'https://imgs.search.brave.com/WeZxsKfA-FDPmSQBym4gohpYVTwWemnGZd2xE-DhLc4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzA3Lzk0LzMzLzUx/LzM2MF9GXzc5NDMz/NTEzOV9jQlJUdXJ3/TXQ5M0pmQVBTQkhm/aWxGaU92N2t3WGFo/NC5qcGc',
        rating: 4.3,
    },
    {
        id: 7,
        name: 'Mushroom Fried Rice',
        description: 'Grilled cottage cheese with a tangy marinade.',
        price: '200',
        isVeg: true,
        image: 'https://imgs.search.brave.com/5PisoGXslRf_PHPgBv_m46GeU2rL1ZS3XNohORWiLy0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/aW5kaWFuaGVhbHRo/eXJlY2lwZXMuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDIx/LzExL211c2hyb29t/LWZyaWVkLXJpY2Uu/d2VicA',
        rating: 4.3,
    },
];

export default sampleFoodData;
